### ISSUE TITLE
recursive enum types will cause stack overflow after setting inline_subschemas

### ISSUE THREAD

**Issue by fikgol** [GREsau/schemars#70]

**Comment by GREsau** [comment]
This should be fixed by 1017506ce6d4855fac247e43acd428d9bbd8fd61, which will be released in v0.8.1

**Comment by GREsau** [comment]
Fixed and published - https://crates.io/crates/schemars/0.8.1

**Comment by Igosuki** [comment]
Sorry to bother, but it still occurs for me, see the following : 
```
#[derive(Clone, Debug, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
pub enum Settings {
    A(OptionsA),
    B(OptionsB),
    C(Box<Settings>),
}
```

```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
```
